---
- name: Install virus scan shell script to be run by systemd service
  ansible.builtin.template:
    dest: /usr/local/sbin/virus_scan.sh
    mode: u=rx,g=,o=
    src: virus_scan.j2.sh

- name: Copy systemd service to run virus scan
  ansible.builtin.copy:
    dest: /etc/systemd/system/run-virus-scan.service
    mode: u=r,g=,o=
    src: run-virus-scan.service
    # I'd like to validate the file here, but that can't be done
    # cleanly.  See ansible/ansible#19243.
    # validate: systemd-analyze verify %s

- name: Copy systemd timer to run virus scan
  ansible.builtin.template:
    dest: /etc/systemd/system/run-virus-scan.timer
    mode: u=r,g=,o=
    src: run-virus-scan.j2.timer
    # I'd like to validate the file here, but that can't be done
    # cleanly.  See ansible/ansible#19243.
    # validate: systemd-analyze verify %s

- name: Enable the systemd timer
  ansible.builtin.systemd_service:
    enabled: true
    name: run-virus-scan.timer
