---
# Unless you do this, systemd can sometimes get confused when you try
# to start a service you just installed
- name: Systemd daemon-reload
  ansible.builtin.systemd:
    daemon_reload: true

# Debian seems to enable the clamav daemon by default
- name: Disable main clamav daemon
  ansible.builtin.service:
    enabled: no
    name: "{{ clamav_service_name }}"

- name: Start and enable freshclam
  ansible.builtin.service:
    enabled: yes
    name: "{{ freshclam_service_name }}"
    state: started
