---
# Unless you do this, systemd can sometimes get confused when you try
# to start a service you just installed
- name: Systemd daemon-reload
  ansible.builtin.systemd:
    daemon_reload: true

# Debian seems to enable the clamav daemon by default
- name: Disable main clamav daemon
  ansible.builtin.service:
    enabled: false
    name: "{{ clamav_service_name }}"
  when: clamav_install_from_package_manager

- name: Create freshclam service file
  ansible.builtin.template:
    dest: /etc/systemd/system/{{ freshclam_service_name }}.service
    group: root
    mode: "0644"
    owner: root
    src: freshclam.service.j2
  when: not clamav_install_from_package_manager and ansible_service_mgr == "systemd"

- name: Start and enable freshclam
  ansible.builtin.service:
    enabled: true
    name: "{{ freshclam_service_name }}"
    state: started

- name: Copy systemd service to run virus scan
  ansible.builtin.copy:
    dest: /etc/systemd/system/run-virus-scan.service
    mode: 0500
    src: run-virus-scan.service
    # I'd like to validate the file here, but that can't be done
    # cleanly.  See ansible/ansible#19243.
    # validate: systemd-analyze verify %s

- name: Copy systemd timer to run virus scan
  ansible.builtin.template:
    dest: /etc/systemd/system/run-virus-scan.timer
    mode: 0500
    src: run-virus-scan.timer.j2
    # I'd like to validate the file here, but that can't be done
    # cleanly.  See ansible/ansible#19243.
    # validate: systemd-analyze verify %s

- name: Enable the systemd timer
  ansible.builtin.systemd_service:
    enabled: true
    name: run-virus-scan.timer
