---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: fedora29_systemd
    image: geerlingguy/docker-fedora29-ansible:latest
    privileged: yes
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    command: /lib/systemd/systemd
    pre_build_image: yes
  # Ansible currently insists on installing python2-dnf, which does
  # not exist in Fedora 30.  Until that is resolved, we can't use
  # Fedora 30.
  # - name: fedora30_systemd
  #   image: geerlingguy/docker-fedora30-ansible:latest
  #   privileged: yes
  #   volumes:
  #     - /sys/fs/cgroup:/sys/fs/cgroup:ro
  #   command: /lib/systemd/systemd
  #   pre_build_image: yes
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: fedora-only-with-cloudwatch-agent
verifier:
  name: testinfra
  directory: ../tests
  lint:
    name: flake8
