---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: ubuntu_bionic_systemd
    image: geerlingguy/docker-ubuntu1604-ansible:latest
    privileged: yes
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    command: /lib/systemd/systemd
    pre_build_image: yes
  - name: ubuntu_xenial_systemd
    image: geerlingguy/docker-ubuntu1804-ansible:latest
    privileged: yes
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    command: /lib/systemd/systemd
    pre_build_image: yes
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: ubuntu-only
verifier:
  name: testinfra
  directory: ../tests
  lint:
    name: flake8
