---
# Frequency of clamav cronjob, must be one of "custom" or a special_time handled by ansible.builtin.cron
clamav_cron_frequency: weekly

# If custom frequency, the role uses this variable to install the cronjob.
# This dict doesn't merge, every line needs to be valuated:
clamav_cron_custom:
  day: "*"
  job: "/usr/local/share/virus_scan.sh"
  minute: "30"
  month: "*"
  hour: "5"
  weekday: "*"

# A dictionary of values to be configured in the clamd and freshclam configuration files.
# Multivalued keys are specified as lists.
# A Nonetype value means that the key will be removed from the file.
# Example:
#
# clamav_freshclam_configuration:
#   DatabaseMirror: ['db.local.clamav.net', 'database.clamav.net']
#   Bytecode: 'true'
#   PrivateMirror:
# clamav_clamd_configuration:
#   LogFile: /var/log/clamav/clamav.log


clamav_freshclam_configuration: {}
clamav_clamd_configuration: {}

# whether or not we create a backup of configuration file before replacing
clamav_configuration_backup: false
clamav_scan_copy: false
clamav_scan_exclude_directories:
  - ^/dev/
  - ^/proc/
  - ^/sys/
  - ^/var/spool/clamav
clamav_scan_extra_flags: []
clamav_scan_move: false
clamav_scan_quarantine_directory: /var/spool/clamav
clamav_scan_quarantine_group: root
clamav_scan_quarantine_mode: 0750
clamav_scan_quarantine_owner: root

clamav_seboolean_name: antivirus_can_scan_system
clamav_seboolean_state: true
