---
# If a systemd host lacks the file /sbin/init, then testinfra
# currently misidentifies it as using SysV.  The relevant code can be
# viewed here:
# https://github.com/philpep/testinfra/blob/master/testinfra/modules/service.py#L51-L63.
#
# The Debian and Ubuntu Docker images that we are using suffer from
# this issue; therefore, we need to install the init package as a
# workaround.  Any real (non-Docker) host will have this package
# installed anyway.
#
# This is a known testinfra issue.  See
# https://github.com/philpep/testinfra/issues/416 for more details.
- name: Group hosts by OS family
  hosts: all
  tasks:
    - name: Group hosts by OS family
      group_by:
        key: os_{{ ansible_facts['os_family'] }}
- name: Install init (Debian)
  hosts: os_Debian
  tasks:
    - name: Install init (Debian)
      package:
        name:
          - init

# The Ubuntu 16.04 Docker image we are using
# (geerlingguy/docker-ubuntu1604-ansible:latest) needs a cache update
# before it can install anything.
- name: Group hosts by OS distribution and major version
  hosts: all
  tasks:
    - name: Group hosts by OS distribution and major version
      group_by:
        key: os_{{ ansible_facts['distribution'] }}_{{ ansible_facts['distribution_major_version'] }}
- name: Update apt cache (Ubuntu 16)
  hosts: os_Ubuntu_16
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
