---
# This molecule configuration file is suitable for testing Ansible
# roles that _do_ require SystemD.  If your Ansible role _does not_
# require SystemD then you should use molecule-no-systemd.yml instead.
#
# Note that the molecule configuration file that is symlinked to
# molecule.yml is the one that will be used.
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - cgroupns_mode: host
    command: /lib/systemd/systemd
    image: geerlingguy/docker-ubuntu2004-ansible:latest
    name: ubuntu-20-systemd
    platform: amd64
    pre_build_image: true
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
  - cgroupns_mode: host
    command: /lib/systemd/systemd
    image: geerlingguy/docker-ubuntu2204-ansible:latest
    name: ubuntu-22-systemd
    platform: amd64
    pre_build_image: true
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
scenario:
  name: ubuntu
verifier:
  directory: ../default/tests
  name: testinfra
