---
# This molecule configuration file is suitable for testing Ansible
# roles that _do_ require SystemD.  If your Ansible role _does not_
# require SystemD then you should use molecule-no-systemd.yml instead.
#
# Note that the molecule configuration file that is symlinked to
# molecule.yml is the one that will be used.
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - cgroupns_mode: host
    command: /lib/systemd/systemd
    image: geerlingguy/docker-fedora37-ansible:latest
    name: fedora37-systemd
    platform: amd64
    pre_build_image: yes
    privileged: yes
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
  - cgroupns_mode: host
    command: /lib/systemd/systemd
    image: geerlingguy/docker-fedora38-ansible:latest
    name: fedora38-systemd
    platform: amd64
    pre_build_image: yes
    privileged: yes
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
scenario:
  name: fedora_modify_config
verifier:
  directory: ../modify_config/tests
  name: testinfra
